### ISSUE TITLE
hpcprof doesn't work optimally given hpcstruct files for libmonitor or libhpcrun

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpctoolkit#308] opened 2020-08-03 23:07 UTC
When hpcstruct is run on libmonitor, the name of a routine "monitor_main" gets replaced with something like "monitor_main [libmonitor.so.1.0.0]". Similarly, in libhpcrun, names like "hpcrun_no_activity" get replaced by "hpcrun_no_activity [libhpcrun.so.1.0.0]".

The NameMapping.cpp code should just match to ensure that the prefix is what we intended. If the suffix (e.g., what appears after monitor_main) begins with a " [", then go ahead and call it a match.

**Comment by blue42u** [comment] 2020-08-04 14:41
Personally, I think we should target a more robust implementation where those "special" and the other "placeholder" CCT nodes are replaced with canonical locations in load module 0 by Run. That would also solve the issue where you get unknown procedures if Prof doesn't have access to `libhpcrun.so` (e.g. when moving the measurements between machines).

Given that new-Prof is on the horizon, I'd rather get these issues fixed by design instead of applying further layers of band-aids to old-Prof (which then have to be ported to new-Prof to stay compatible).

**Comment by jmellorcrummey** [comment] 2020-08-04 15:11
point well taken. a redesign is fine.

**Comment by blue42u** [comment] 2022-08-18 22:37
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/308)

**Closed by blue42u** 2022-08-18 22:37 UTC
