### ISSUE TITLE
missing line map with discriminator from ibm clang on power8/le

### ISSUE THREAD

**Issue by mwkrentel** [HPCToolkit/hpctoolkit#65] opened 2018-03-23 04:27 UTC
There is a problem where the IBM clang compiler on power8/le creates
debug info with the tag 'discriminator' (whatever that means) that
causes dyninst to miss some line map info, especially around loop
headers.

The problem could be in either in dyninst or libdw, I haven't
investigated.  This example is with hpctoolkit mult-kernel and dyninst
master, so libdw, not libdwarf.

For example, in the lulesh2.0 binary, objdump reports:

/ccs/home/kz21/Codes/llvm/hpctoolkit-gpu-samples/target_lulesh/lulesh.cc:1470 (discriminator 5)
    10013210:   6c 01 7f 80     lwz     r3,364(r31)
    10013214:   58 01 9f 80     lwz     r4,344(r31)
    10013218:   00 20 03 7c     cmpw    r3,r4
    1001321c:   fc 00 81 41     bgt     10013318 <.omp_outlined._debug__.91+0x398>

But what I get from symtab is no line map info:

   stmt:  0x10013210 (4)  l=0  f=''
   stmt:  0x10013214 (4)  l=0  f=''
   stmt:  0x10013218 (4)  l=0  f=''
   stmt:  0x1001321c (4)  l=0  f=''

I've copied the lulesh2.0 binary along with a struct file and objdump
output on po in:

po:  ~krentel/discrim-line-map

**Comment by jmellorcrummey** [comment] 2018-04-13 12:43
From the DWARF 5 standard:

**discriminator:**  An unsigned integer identifying the block to which the current instruction belongs. Discriminator values are assigned arbitrarily by the DWARF producer and serve to distinguish among multiple blocks that may all be associated with the same source file, line, and column. Where only one block exists for a given source position, the discriminator value is be zero.

Since readelf reads and prints information about discriminators, I suspect that the problem is not libdw but rather Dyninst. For our purposes, Dyninst could ignore them. I will investigate why it doesn't seem to handle them.

**Comment by jmellorcrummey** [comment] 2018-06-30 19:47
fixed in GitHub.com/jmellorcrummey/dynint master commit 40e981fdb296a0de083259b5a95392dcab223a69

**Comment by blue42u** [comment] 2022-08-18 22:38
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/65)

**Closed by blue42u** 2022-08-18 22:38 UTC
