### ISSUE TITLE
we missed a place where vdso names need to be prettified

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpctoolkit#211] opened 2020-02-14 13:56 UTC
we need to prettify the vdso load module name when creating unknown procedure names in hpcprof

<img width="636" alt="image" src="https://user-images.githubusercontent.com/3926112/74537229-4e916580-4eff-11ea-9ad1-3d3f1032f7f0.png">

**Comment by mxz297** [comment] 2020-02-16 18:10
@jmellorcrummey I am having difficulty of reproducing this problem. When I ran my small CUDA example with `hpcrun -t -e REALTIME -e gpu=nvidia` with the latest master branch, the flat view I saw is as follows:

![image](https://user-images.githubusercontent.com/1683713/74610016-17fd4b80-50b5-11ea-98fe-2e2883cfdcfa.png)

You can see that there are not `<unknown procedure>` entries in my viewer. Did you run hpcstruct on the vdso file?

**Comment by jmellorcrummey** [comment] 2020-02-16 20:30
@blue42u Can you provide Xiaozhu your deep wave measurements directory related to the issue I reported here? Xiaozhu doesn't need any binaries because the attribution problem surfaced with the vdso file in your measurements directory.

**Comment by mxz297** [comment] 2020-02-18 03:10
@jmellorcrummey 
![image](https://user-images.githubusercontent.com/1683713/74700545-8a5f5000-51c9-11ea-8102-442222174b88.png)

I got the vdso name normalized. However, I find that there is a "unknown load module" in my viewer. I am not sure if it is normal, or if it is caused because I got a moved directory, or if it is a bug.

**Comment by jmellorcrummey** [comment] 2020-02-18 03:20
I think the unknown load module occurs because there are load modules that are missing. The missing load modules can be found on Jonathon’s home system, but not where you were doing this work. Your result looks good. i will look at the commit carefully to see where changes were needed.

**Comment by blue42u** [comment] 2020-02-18 03:41
The `<unknown load module>` occurs on my system too, Prof uses the path of the load module if it can't find it (and spits out `<unknown procedure> 0xXXX [LM]` tags).

Those are the bad unwinds, the unwinder lands in a region with apparently no load module. The logs show some very interesting addresses, some of which are obvious errors (like `0x1000`), but some look important (like `0x7f65a28b46fa`, from `libstdc++` at `0x7f65d679af75`).

Which is why I asked at the last meeting exactly how gracefully Run fails if Fnbounds crashes while analyzing a module.

**Comment by mxz297** [comment] 2020-02-21 20:01
@jmellorcrummey Can we close this issue?

**Comment by mxz297** [comment] 2020-02-26 21:30
Fixed by #228

**Closed** 2020-02-26 21:31 UTC
