### ISSUE TITLE
2unwinders doesn't properly generate normalized IPs

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpctoolkit#38] opened 2017-12-04 01:12 UTC
(1) To support backtrace, the cursor is always supposed to have a normalized IP for the cursor and for the function. to maintain this invariant, the binary analyzer version computed a normalized IPs first as the cursor was initialized and then after each step. This is not currently done for the libunwind cursor initialization used on x86.

(2) The process used to compute the normalized IP after a step in libunwind uses unwr_info associated with the PC before the step. before computing a normalized IP after a step, the unwinder needs to look up the recipe that applies to the new PC.

(3) To compute the recipe at each step, the framework needs to be able to try each unwinder to see if it can compute a recipe. The unwinder currently looks up a recipe before each step operation. Instead, this should be done at the end of each step operation to compute the unwind recipe for the new PC that was the result of the step. Which unwinder will yield a valid recipe at that point? It could be either. So, I believe that rather than having the stepper in charge of picking which unwinder is next, this should be done in a wrapper around unw_recipe_map_lookup. There should be a version of this utility that doesn’t take an unwinder as an argument. Instead, in the 2unwinders case, it should try to look up a recipe using DWARF first. If that doesn’t work, it should revert to the binary analyzer. That way, this composite recipe discovery routine can be called from cursor initialization and then at the end of each step. It’s return value should inidicate which unwinder produced the recipe so that it knows which unwinder should be applied to the recipe stored in the cursor. A recipe should be stored in the cursor so that we don’t have to look up a recipe twice  - once to compute the unwr_info needed to compute the normalized IP for the PC in the cursor and the enclosing function and again to unwind from that PC in the next unwind step.

**Comment by unkadoug** [comment] 2017-12-04 04:38
In response to (1):
It is true that the libunwind cursor initialization use on x86 does not maintain any invariants related to x86 unwinding.  That is because, if libunwind works all the time, no work related to x86 native unwinding is supposed to be done.  If the first libunwind step fails, the code seeks to initialize the x86 cursor state for a first x86-native step:

 if (STEP_ERROR != unw_res)
    return (unw_res);
  save_registers(cursor, pc, bp, sp,
                 cursor->libunw_status == LIBUNW_OK ? (void *)(sp - 1) : NULL);

where, for the first step, libunw_status is LIBUNW_INIT and so ra_loc is set to NULL.

Maybe this is being done incorrectly?  Or libunwind is giving bad value for pc, bp and sp?  But the issue isn't being ignored, and I don't want to be doing native-x86 unwinding work in cases where libunwind is working fine and we don't need to fallback to native-x86 unwinding.

I'll study points (2) and (3) and perhaps followup on them later.

**Comment by jmellorcrummey** [comment] 2017-12-04 05:49
When the cursor is initialized, it is supposed to be recorded in the call stack as the leaf of a call path. There needs to be a normalized IP for the PC in the cursor and a normalized IP for the first address in the function containing the PC. That is what I meant by comment (1). I don't see how this can be skipped.

**Comment by unkadoug** [comment] 2017-12-04 07:24
In response to (2):
It seems that this would be addressed by moving the call to compute_normalized_ips in libunw_unw_step up a few lines, to before the call to unw_apply_reg_state.

**Comment by unkadoug** [comment] 2017-12-04 07:41
How do I reproduce this bug and test a fix for it?  I'm not too keen on the proposal of (3), which is stateful, and backwards, in my opinion.  I'd like to see if I could solve the problem without all that, and test the solution before checking it in.

**Comment by jmellorcrummey** [comment] 2017-12-05 04:53
I tested it on hpcstruct. To rigorously test it, you can create three shared libraries, each containing a single function. 

Library L1 contains function “a”
Library L2 contains function “b”
Library L3 contains function “c”

Main calls a; a calls b; b calls c;
Main, a, b, and c each contain a loop surrounding their call.

**Closed** 2017-12-11 22:56 UTC
